// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/crypto.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_EnkraSecureChannelKeyPtr =>
          wire.rust_arc_decrement_strong_count_RustOpaque_EnkraSecureChannelKey;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_MutexStdRngPtr =>
          wire.rust_arc_decrement_strong_count_RustOpaque_MutexStdRng;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_XChaCha20Poly1305Ptr =>
          wire.rust_arc_decrement_strong_count_RustOpaque_XChaCha20Poly1305;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  EnkraSecureChannelKey dco_decode_RustOpaque_EnkraSecureChannelKey(
      dynamic raw);

  @protected
  MutexStdRng dco_decode_RustOpaque_MutexStdRng(dynamic raw);

  @protected
  XChaCha20Poly1305 dco_decode_RustOpaque_XChaCha20Poly1305(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AeadCipher dco_decode_aead_cipher(dynamic raw);

  @protected
  AeadCipher dco_decode_box_autoadd_aead_cipher(dynamic raw);

  @protected
  SecureChannelCipher dco_decode_box_autoadd_secure_channel_cipher(dynamic raw);

  @protected
  EncappedKey dco_decode_encapped_key(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  SecureChannelCipher dco_decode_secure_channel_cipher(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  EnkraSecureChannelKey sse_decode_RustOpaque_EnkraSecureChannelKey(
      SseDeserializer deserializer);

  @protected
  MutexStdRng sse_decode_RustOpaque_MutexStdRng(SseDeserializer deserializer);

  @protected
  XChaCha20Poly1305 sse_decode_RustOpaque_XChaCha20Poly1305(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AeadCipher sse_decode_aead_cipher(SseDeserializer deserializer);

  @protected
  AeadCipher sse_decode_box_autoadd_aead_cipher(SseDeserializer deserializer);

  @protected
  SecureChannelCipher sse_decode_box_autoadd_secure_channel_cipher(
      SseDeserializer deserializer);

  @protected
  EncappedKey sse_decode_encapped_key(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  SecureChannelCipher sse_decode_secure_channel_cipher(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_EnkraSecureChannelKey(
      EnkraSecureChannelKey self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_MutexStdRng(
      MutexStdRng self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_XChaCha20Poly1305(
      XChaCha20Poly1305 self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_aead_cipher(AeadCipher self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_aead_cipher(
      AeadCipher self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_secure_channel_cipher(
      SecureChannelCipher self, SseSerializer serializer);

  @protected
  void sse_encode_encapped_key(EncappedKey self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_secure_channel_cipher(
      SecureChannelCipher self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_EnkraSecureChannelKey(
          int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_EnkraSecureChannelKey(
              ptr);

  void rust_arc_decrement_strong_count_RustOpaque_EnkraSecureChannelKey(
          int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_EnkraSecureChannelKey(
              ptr);

  void rust_arc_increment_strong_count_RustOpaque_MutexStdRng(int ptr) =>
      wasmModule.rust_arc_increment_strong_count_RustOpaque_MutexStdRng(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_MutexStdRng(int ptr) =>
      wasmModule.rust_arc_decrement_strong_count_RustOpaque_MutexStdRng(ptr);

  void rust_arc_increment_strong_count_RustOpaque_XChaCha20Poly1305(int ptr) =>
      wasmModule
          .rust_arc_increment_strong_count_RustOpaque_XChaCha20Poly1305(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_XChaCha20Poly1305(int ptr) =>
      wasmModule
          .rust_arc_decrement_strong_count_RustOpaque_XChaCha20Poly1305(ptr);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
      rust_arc_increment_strong_count_RustOpaque_EnkraSecureChannelKey(int ptr);

  external void
      rust_arc_decrement_strong_count_RustOpaque_EnkraSecureChannelKey(int ptr);

  external void rust_arc_increment_strong_count_RustOpaque_MutexStdRng(int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_MutexStdRng(int ptr);

  external void rust_arc_increment_strong_count_RustOpaque_XChaCha20Poly1305(
      int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_XChaCha20Poly1305(
      int ptr);
}
